import React from "react";

function page() {
  return (
    <div>
      <div className="rounded-xl border border-border bg-card p-5 text-card-foreground">
        <p className="text-sm text-muted-foreground">Total Leads</p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores nam placeat quia dolore, esse distinctio amet quae quam fuga ducimus architecto suscipit quos nisi quidem sunt ratione rerum. Sit, quia?
          Facilis magnam quia repellat, tenetur perspiciatis, dolorum amet quisquam vel cum accusantium, unde quas adipisci placeat nam quae quod quaerat aspernatur voluptates. Ad eveniet sed, dolores praesentium asperiores voluptatum enim?
          Veritatis necessitatibus distinctio eligendi, pariatur perspiciatis expedita reiciendis, dolorum vel sed est deleniti, voluptas corrupti in inventore ipsam. Ullam provident aut sed sit vitae voluptatem quis cupiditate? Aspernatur, at provident.
          Quae saepe deserunt sunt autem unde quis illo expedita ipsum velit eum maiores, est natus ad voluptas? Beatae corrupti inventore rem recusandae mollitia? Quod dolor ut sapiente corrupti distinctio alias!
          Deleniti veniam culpa fugit assumenda molestiae aliquam ut, qui accusamus consequuntur repudiandae iure, magni velit eius iste beatae hic animi omnis error ullam. Placeat rerum, natus unde ex magnam numquam.
          Itaque vero cum mollitia fugit nostrum soluta quis officia tempore ex ad! Fuga ipsam quaerat, placeat doloremque explicabo repellat commodi, sit reprehenderit ducimus itaque nostrum voluptatum earum, laboriosam minus est!
          Saepe repellat nulla blanditiis, ab, qui, iusto temporibus maxime accusantium modi perferendis placeat fugiat eius quae consectetur hic quia sequi quibusdam? Inventore laboriosam nesciunt sapiente sit, corrupti mollitia commodi veritatis?
          Dolorem cupiditate ratione, iusto adipisci dolores ullam accusantium autem maxime pariatur ipsam saepe deserunt in officiis inventore expedita corrupti enim quae. Fuga ullam unde magni eos voluptate. Vel, perspiciatis ducimus.
          Quae sequi iusto earum ut id cumque temporibus. Aliquam consequuntur dolorum, dicta doloremque ad laudantium, non ipsum minus magnam optio sint. Dolorem eos voluptatibus ipsum a eius quia facere autem.
          Ipsam, minus odio porro, ratione unde magnam id facere provident beatae reprehenderit dolores at cum earum est quia non dolorem! Sapiente quas natus dolore saepe blanditiis labore accusamus, vero qui.
          Harum excepturi placeat ipsa a quas eum eligendi dolor. Molestiae consequatur explicabo suscipit cupiditate? Doloribus cumque provident laboriosam repudiandae velit explicabo! Saepe aperiam possimus quia deleniti sapiente, qui mollitia repudiandae.
          Ad dolores commodi velit praesentium amet quod distinctio quas labore beatae. Vero libero debitis animi saepe cumque ipsum earum eos iure, temporibus dolores accusamus voluptates pariatur dolore esse quaerat soluta.
          Ab sunt, fugiat, ipsa recusandae nihil temporibus pariatur debitis cum, amet iste necessitatibus assumenda ad quibusdam impedit et laudantium voluptate rem exercitationem quod voluptas! Quos sint in dolore cupiditate vero.
          Blanditiis facilis, consectetur ex facere possimus sequi nihil iure minima molestias corporis dolorum dolore dolores aperiam ipsa commodi iusto enim necessitatibus veritatis quaerat. Et dolorum reiciendis optio eum eaque quia.
          Expedita eaque itaque id, pariatur sunt exercitationem optio laborum provident voluptates, officiis mollitia quia velit iusto, tempore esse corporis asperiores dolorum corrupti ipsam! Tenetur molestiae quisquam libero consequatur repudiandae provident.
          Impedit voluptates omnis provident aspernatur ipsa quasi id atque magnam facilis aut, maiores esse, voluptatibus amet minima rerum ipsam qui commodi laudantium veniam quae itaque nihil quidem odit. Autem, explicabo!
          Magni, consectetur, pariatur minima repellendus vel perspiciatis dicta culpa obcaecati dolorem maxime neque debitis nesciunt enim voluptatem repudiandae necessitatibus fugit facere saepe assumenda. Esse mollitia maxime amet, ullam saepe praesentium.
          Deleniti rerum, corporis reiciendis ullam voluptatem laudantium pariatur ipsam ab neque est dicta unde doloremque natus sequi voluptatibus quo animi, labore fugit? Quasi reiciendis nihil maiores veritatis consequuntur voluptates nisi!
          Cumque quas nemo itaque ad veritatis distinctio aperiam, minus eum earum aspernatur quibusdam. Quae quisquam tempora ipsa id, repudiandae, nisi tempore mollitia molestiae adipisci quas in quasi saepe doloribus fugiat?
          Cumque quasi perferendis natus inventore velit accusantium iste. Debitis quasi exercitationem nihil, impedit autem aut accusamus commodi iure praesentium nostrum alias ipsum ab eveniet illum amet accusantium quidem deserunt optio?
          Maxime tempora, facere assumenda, voluptatem ratione dolore eos qui vitae nesciunt deserunt odio iure nihil, consequuntur perferendis accusamus eaque libero quisquam eum corrupti sit ad ea at ex. Deleniti, magni.
          Perspiciatis animi perferendis obcaecati magni odio. Dolor distinctio rem maxime dolorum molestias tempora ipsum laboriosam expedita hic? Voluptatem, beatae voluptas? Incidunt magni tenetur sapiente nam mollitia perferendis beatae dolor est.
          Tenetur iste ab illum sint veniam, aliquid ullam porro iusto, debitis itaque asperiores error id fuga sapiente quasi unde quam perferendis atque vitae dolorum deleniti iure. Dicta neque quasi officia?
          Assumenda maiores, similique dicta ex repudiandae, quis illo animi molestiae sequi asperiores illum repellendus labore excepturi. Soluta asperiores quam perspiciatis, et minima a consequuntur totam quos est sit. Cum, quae.
          Ducimus similique non, explicabo eius, ratione impedit fugiat doloribus officia omnis repudiandae asperiores nobis voluptates sed et iure, fuga corporis hic eum tenetur natus nihil sapiente sequi provident illo. Sequi!
          Porro iusto quos omnis facere, tempore nam voluptates inventore ullam aliquam eaque. Molestiae repellendus, deleniti doloremque dicta labore aliquam voluptate mollitia suscipit placeat id laudantium temporibus iste, ipsa at natus.
          Numquam beatae nisi accusantium placeat fugit ipsam repellat cumque adipisci alias similique dolorem distinctio, id debitis temporibus nulla molestias odio nesciunt qui magni? Dicta nobis explicabo perspiciatis optio repellendus id.
          Explicabo maxime unde, ex nisi vero libero eaque alias facilis magni iure veritatis assumenda nam culpa neque molestiae quibusdam eligendi expedita pariatur. Impedit modi deserunt nihil, exercitationem accusantium commodi quis.
          Sit aliquam odio et ratione maxime doloribus quasi voluptas explicabo, aspernatur impedit culpa deserunt illo accusantium vero sapiente similique. Aspernatur aut perspiciatis at, sed nulla ducimus doloribus sint fuga provident.
          Ut odit aut praesentium minus accusantium consequatur fuga rem optio, corrupti cumque dolorem voluptatum nisi, eveniet quod perspiciatis? Accusantium id quisquam inventore rem quos eos in soluta harum adipisci quod?
          Rem amet necessitatibus exercitationem assumenda in quam modi quibusdam optio aperiam, blanditiis pariatur hic saepe enim excepturi libero, perspiciatis corporis! Voluptatum voluptate quibusdam culpa adipisci iure ea blanditiis voluptates reiciendis.
          Placeat sint expedita consequatur inventore culpa dignissimos mollitia, saepe aut qui debitis exercitationem fugiat. Quos excepturi voluptates nam eum nulla debitis pariatur eligendi, exercitationem at culpa odit ullam. Porro, omnis.
          Fuga illum nobis porro ullam officia dicta repellat voluptatum, sit non quam fugit, velit est! Consectetur sapiente quisquam fugiat, impedit amet rerum quaerat voluptatem, omnis ducimus, perspiciatis quidem vitae? Eveniet.
          Ex, explicabo. Deserunt fugiat repellendus, quas beatae animi pariatur, libero fugit velit voluptatibus odio maxime totam ab! Quod iure, magnam nobis est nihil esse hic at, officia repudiandae, doloremque id.
          Perferendis impedit at facere doloremque laboriosam. Ad perspiciatis quis corporis! Esse culpa dolor minus? Hic numquam libero saepe doloremque id obcaecati eligendi placeat accusantium. Aliquid vel possimus praesentium blanditiis commodi.
          Ea repellendus ipsa mollitia magnam suscipit, consequuntur tempora sequi voluptatem inventore possimus ex sapiente soluta repellat quis non aspernatur a aliquam qui esse, aliquid reiciendis distinctio nulla vero sit. Dignissimos!
          Ipsum minus fugiat sunt hic nam quibusdam vel adipisci enim impedit debitis illum odio corporis cumque quia aperiam culpa, totam nemo non exercitationem tenetur minima! Nulla iste incidunt dolorem corrupti.
          Consequatur voluptas, non, sint, eos recusandae aspernatur fuga vitae repellat accusamus vero dicta nisi molestias libero autem voluptatem temporibus! Molestias accusantium voluptate rem dolor, expedita animi aperiam fugiat repudiandae repellat?
          Enim dignissimos magnam recusandae maxime molestias aliquam animi, reiciendis ipsam nam eveniet excepturi voluptatibus rerum laborum optio consequatur. Labore iure nobis rem rerum facilis autem repellat quidem fuga id aspernatur!
          Veritatis ea ipsum possimus, adipisci sunt quos omnis facilis dicta unde itaque accusantium voluptates excepturi. Officia modi error quidem, libero unde nulla iure in repellendus commodi asperiores corporis assumenda doloribus.
          Quasi optio enim ex, repellat similique est exercitationem maiores aut ipsam molestias, nostrum, veritatis quo quidem? Fugit, eius optio eaque nobis aliquam ipsam! Nemo, facere! Asperiores beatae a saepe laudantium!
          Itaque asperiores soluta cumque distinctio accusantium, at laboriosam voluptatem architecto placeat quam doloremque ipsam dolorem reiciendis commodi omnis nobis! Quis quasi minus aliquam, magnam veritatis voluptates? Distinctio iure quibusdam quam!
          Suscipit accusantium autem velit animi, aliquid magnam modi corporis maxime quis iusto quod sed reiciendis, sapiente praesentium repudiandae porro minus? Deserunt modi architecto molestiae vero sequi, quisquam fugit consectetur. Ut.
          Asperiores laborum minus adipisci numquam rem quibusdam optio at quasi commodi cum recusandae, cumque iste, placeat velit. Molestias ut esse dolorum quasi expedita ratione, a perferendis ipsum voluptas consequuntur magni.
          Velit delectus maxime corporis atque? Repellat quae dolor odit molestias quod deserunt nesciunt quaerat consequatur explicabo laboriosam atque sint totam modi, inventore suscipit minima culpa nostrum. Qui quia assumenda quas?
          Neque dicta iure aspernatur? Dolor cum excepturi accusantium deleniti voluptatibus sapiente accusamus recusandae aut? Ipsum asperiores explicabo eveniet nesciunt ratione vitae, voluptates amet aut architecto, reprehenderit aspernatur qui laboriosam ut.
          Voluptas voluptatibus impedit vitae adipisci optio sequi error, omnis excepturi repudiandae pariatur et. Accusamus quia facilis perspiciatis ratione. Distinctio consequuntur cumque asperiores doloremque maxime officia error, deleniti voluptas eum recusandae.
          Deserunt quas nam earum labore animi? Quam, iure iste! Placeat inventore ex provident? Tenetur blanditiis, velit doloribus eum voluptatibus saepe porro veniam, minus repellat impedit ratione, maiores natus voluptates accusantium.
          Magni facere fuga nostrum labore, voluptas, et sapiente est dolore maiores, omnis soluta magnam? Reprehenderit qui eveniet hic repellat debitis dolore, dolores quis vel numquam ullam doloremque sequi laborum neque?
          Obcaecati doloremque harum adipisci officia, assumenda ex non necessitatibus ab beatae vitae. Aspernatur beatae, animi voluptatem voluptate perferendis mollitia quaerat non veniam architecto, rem modi ea aliquam ut laboriosam odio.
          Harum odit excepturi distinctio quam nisi nesciunt tenetur sequi, quibusdam beatae voluptatum placeat omnis maiores vel! Consequatur dolore labore sint aliquam at! Quos debitis amet quia hic molestiae iure ea!
          Tempore voluptatum velit ab veritatis porro, deleniti perspiciatis illo sed quibusdam, molestiae rem ut officiis, nemo explicabo vero maiores quia nesciunt voluptatibus! Rem cum modi soluta in impedit sit nobis.
          Quae repudiandae hic minus laboriosam iusto et provident eos omnis, adipisci aliquam repellendus nemo aperiam ipsam quisquam officiis illo non reiciendis libero id sunt, sapiente recusandae quod! Inventore, velit aut.
          Aut culpa maiores quaerat, illo sequi placeat rem expedita assumenda magnam voluptates officia libero eius, voluptate sapiente, repellat ipsam minus harum? Odio id ab similique laboriosam voluptas corporis magnam adipisci.
          Corrupti quas animi rerum, obcaecati nobis sunt assumenda voluptas saepe cupiditate illo veritatis labore. Est officia nobis laudantium perferendis similique adipisci, molestias soluta in cupiditate iusto animi impedit. Saepe, deleniti!
          Modi excepturi maiores voluptatibus id suscipit quia voluptatem ex eaque? Aspernatur ut ullam sed voluptatum! Soluta, voluptas deleniti. Expedita quos est aliquam sapiente, tempore quasi molestias obcaecati minima vel praesentium!
          Perspiciatis beatae animi, dolor explicabo nisi quam delectus maxime, iure facilis nostrum accusamus natus laborum inventore eaque debitis asperiores culpa cupiditate accusantium sed incidunt totam harum quo omnis. Sapiente, accusantium.
          Minima iusto atque odit. Repudiandae odio tempora veniam cumque quis unde, dolores optio quibusdam. Maiores id labore commodi? Earum possimus expedita esse obcaecati? Voluptatum asperiores voluptates repudiandae ut aspernatur harum?
          Libero modi, quod eaque dolore aut rerum cum deleniti facere ducimus. Qui perferendis est necessitatibus sint culpa. Eaque non ipsum at officia iusto porro illum eos, unde inventore ipsa cumque.
          Quam excepturi nisi inventore eligendi tempora architecto neque odio id dolores sint fugiat harum, delectus, molestiae vitae! Odit vitae laborum quasi praesentium, commodi dolorum quod quis unde. Culpa, perferendis quibusdam.
          Repudiandae, labore! Nisi obcaecati cum cumque. Minus eaque, minima dignissimos vel tempora nisi quia quae placeat ea impedit maxime est necessitatibus. Aliquam perspiciatis illum enim accusantium, mollitia minima assumenda cupiditate.
          Vitae quae ipsum autem nostrum architecto voluptas sunt quo in aliquid, modi, officiis fuga quaerat accusantium cupiditate esse? Quam dicta, non eligendi est cumque nemo incidunt quas eaque et consectetur!
          Eaque eum sint doloribus quae sed earum ea illo voluptas culpa odit magnam qui, fugiat dignissimos? Eos consequuntur eligendi et eius expedita id odio illo! Assumenda optio nisi ab nobis?
          Sit, voluptatem commodi! Quo, ullam dolor fuga earum pariatur explicabo reiciendis consequuntur! Ea dolorem, quos debitis, dolore commodi voluptate ducimus ab, quaerat tempore nisi minima quo sunt nulla rerum? Vero.
          Asperiores, eaque sint culpa fugit harum molestias facilis aspernatur modi officiis nesciunt quas suscipit, reiciendis sit aperiam placeat consectetur reprehenderit iure aut illum error, ipsam deserunt beatae hic deleniti! Reprehenderit.
          Provident illum explicabo corporis recusandae libero? Pariatur magnam veritatis numquam temporibus enim autem unde, quas quia quam, cumque quo molestiae molestias aspernatur qui maiores. Autem minima reprehenderit ex. Distinctio, voluptatem!
          Alias architecto nemo eligendi deserunt esse, sequi soluta sunt sapiente iusto tempora, commodi, dignissimos voluptate enim? Quam dolore, sit et nobis earum, tempora molestias porro quo maxime deleniti dolorem! Quaerat.
          Fuga rerum ad, quisquam iusto laudantium quas, voluptas iure voluptate impedit, voluptatem placeat fugiat recusandae minus maxime magni? Soluta atque maiores voluptatem molestias nisi nobis et aspernatur necessitatibus eius dignissimos.
          Veniam nemo sed, facilis officia itaque quas necessitatibus esse, quam, neque corrupti soluta! Distinctio quibusdam iste et tempora aspernatur nulla obcaecati necessitatibus suscipit magnam exercitationem dicta modi laborum, vero est!
          Corrupti vero, deleniti odit enim ipsum, ipsa architecto illo facilis ab natus quos sit necessitatibus ratione voluptates. Soluta, error? Quibusdam labore hic explicabo eius maxime officiis odio ad, quos sit.
          Id illum officiis molestias suscipit dolorem? Molestiae ex voluptas accusantium praesentium perspiciatis, voluptatum nisi exercitationem consectetur. Asperiores numquam dolorem reprehenderit, corrupti excepturi tenetur accusamus eos quisquam deleniti eius? Fugiat, sint.
          Aliquid expedita nobis, maxime assumenda quia perferendis minus distinctio. Totam adipisci, dolor rerum saepe, eaque sunt itaque quibusdam cupiditate aliquid, id culpa. Esse molestias, provident autem perferendis fugit cumque temporibus?
          Repellat rerum numquam architecto asperiores sit labore dolor doloribus autem, nesciunt quod. Quisquam sit eius odio totam, omnis corporis natus in iure culpa consequuntur distinctio tempore nihil consequatur debitis laboriosam!
          Aut nemo omnis maiores iusto placeat asperiores illo ex quibusdam aliquam. Est provident at mollitia accusamus rem iste culpa fuga distinctio eos debitis. Numquam molestias dolor alias architecto quaerat ratione!
          Iure placeat vel sapiente quidem dolore dicta itaque magni, nulla, optio possimus distinctio omnis saepe provident aliquam maiores consequatur molestias, voluptatibus ex dignissimos eveniet! Nobis voluptate ea laudantium quae dolorem.
          Veniam, doloribus hic! Doloremque omnis repudiandae placeat eaque recusandae architecto dolor voluptatem saepe ullam voluptatum possimus aliquid expedita, rerum explicabo eum delectus optio? Veritatis doloremque deserunt ratione error nisi adipisci?
          Tenetur vero ipsa fuga iure voluptate quidem adipisci, accusantium odit. Odio asperiores dolorem dolore cumque est consequuntur natus obcaecati, recusandae provident, quae sed, maxime error. Eius, labore! Necessitatibus, ducimus ratione.
          Ipsum, impedit! Perspiciatis perferendis odio ducimus fugiat. Ipsum vero sit laudantium cupiditate soluta! Blanditiis quae minima corrupti, aspernatur minus adipisci voluptatum tempora unde perspiciatis. Cum voluptate ad velit dicta animi!
          Rerum voluptate, voluptatum libero eligendi perspiciatis quisquam culpa? Temporibus, nulla. Quasi, tempore eius repellat provident nisi beatae ea dolores suscipit fuga unde corporis voluptas perferendis iste, aspernatur, quisquam neque eveniet!
          Similique deleniti eveniet illo veritatis nam ipsam temporibus, dolor tempora. Impedit, rem at. Quas mollitia, excepturi velit officia recusandae maxime omnis quam rem necessitatibus similique. Eligendi eos at et id.
          Atque dolore dolorum numquam consequatur. Inventore corrupti nisi corporis dolor molestiae quo explicabo aliquid quibusdam voluptas a ut, molestias est adipisci dignissimos animi expedita blanditiis in porro architecto repudiandae repellendus?
          Excepturi recusandae quis ipsum iste corporis quia inventore, facilis necessitatibus reprehenderit non amet, architecto accusantium laboriosam voluptatum illum obcaecati! Aut rem ratione adipisci unde, alias ab consequuntur itaque? Sit, architecto?
          Consequuntur aut fuga nisi perspiciatis saepe vel ratione commodi explicabo omnis, fugit sapiente voluptatem. Rerum inventore assumenda nisi ut eum perspiciatis sed, nihil, porro eligendi accusantium temporibus dolore ad tenetur?
          Incidunt quam similique quasi expedita rem molestias harum officiis. Placeat saepe exercitationem distinctio, dicta, delectus eius quaerat vero repellendus magni suscipit et, perferendis neque inventore a reprehenderit quas cupiditate aliquid.
          Nisi molestiae expedita voluptates nesciunt iure inventore ab quas sunt doloribus pariatur. Consequatur repellendus nobis nostrum nesciunt suscipit autem nulla dolorem sunt, molestias beatae sint ad vitae obcaecati dolore maxime.
          Perspiciatis, voluptatem. Perspiciatis, quas explicabo! Molestiae officiis assumenda iusto quasi consectetur dolor harum, ad aspernatur numquam. Porro cum quis pariatur deserunt dignissimos aspernatur adipisci, nesciunt, aut, hic dolorum fugiat provident!
          Veritatis itaque corrupti sunt nihil pariatur excepturi? In odio blanditiis quo ipsam fugiat minima, culpa tenetur molestias corporis laborum aperiam consectetur est autem itaque unde quidem recusandae iure quas voluptatem?
          Recusandae dignissimos, quibusdam corrupti labore fugiat consequatur dolor, assumenda dolore facere quo voluptates vero veritatis adipisci nisi aliquid, a provident debitis accusantium veniam illum? Perspiciatis dicta esse consectetur quia voluptas?
          Ducimus itaque cumque harum, repellendus quibusdam modi corporis sed consectetur quas beatae illo recusandae, quia explicabo necessitatibus autem, natus aut suscipit velit! Aliquam, facilis at veniam molestiae iure quisquam ut.
          Unde esse voluptates harum nesciunt aliquam soluta, commodi quidem, culpa aliquid doloremque perspiciatis ducimus possimus totam dicta dignissimos! Provident sequi tenetur quam accusantium delectus harum maxime cupiditate laborum ex aut.
          At minima optio blanditiis dolorum laudantium nesciunt, necessitatibus doloribus, veritatis praesentium in illo ea cupiditate atque magni numquam tenetur quod! Asperiores, expedita nisi doloremque mollitia placeat id sit. Sint, maiores!
          Id neque quidem aperiam iusto! Tenetur incidunt ab enim, quo distinctio libero fugit neque possimus facere, iusto eos, quas exercitationem? Aut totam officiis similique deserunt repudiandae omnis esse deleniti illum!
          Repellat sit, sed illo impedit nisi iusto quas maxime. Necessitatibus quisquam itaque repellat esse laborum quae, molestiae autem sapiente porro neque, totam suscipit earum tenetur temporibus. Cum repellendus a vero!
          Nesciunt nihil, atque commodi vel iste accusantium maiores eum nemo. Fuga id officiis fugiat ullam delectus voluptatum culpa nostrum consequatur quod dolor in dolorem, quasi amet est enim magni necessitatibus!
          Molestias dolorum quisquam alias veritatis, ut iste odit iure quia error. Expedita ex, voluptatem ullam saepe laborum maxime fugiat qui corporis quos non aperiam est excepturi minus ducimus dolores ipsam?
          Cupiditate temporibus, porro placeat inventore nobis quae magnam illum molestias in reiciendis enim cum praesentium dolorum. Repellendus mollitia itaque omnis beatae dolorum quaerat inventore. Temporibus in eos sequi. Fuga, odit.
          At voluptas assumenda fugiat illum, fuga pariatur dolores, error sed recusandae quidem laboriosam neque doloribus aperiam est! Beatae, magnam doloribus velit facere odit officiis quam exercitationem numquam optio corporis iure?
          Atque in aut animi doloribus mollitia quibusdam saepe illum, corporis quas alias nulla eveniet soluta dolore quos. Quia commodi quisquam, suscipit, eaque praesentium, vel perspiciatis rerum autem asperiores alias facilis.
          Placeat hic perspiciatis eos iusto facere, dolore aut debitis cumque nesciunt aperiam. Natus ex commodi repellat fugit veritatis, explicabo doloremque aut vitae obcaecati facilis, iste voluptatem cupiditate vero rem corporis?
          Molestias nostrum nesciunt quisquam atque, ratione non officiis voluptatum, eius modi delectus molestiae dolor vero velit totam unde maxime. Iure mollitia tempore asperiores quidem. Necessitatibus eum doloremque harum perspiciatis unde.
        <h2 className="mt-2 text-2xl font-semibold">1,248</h2>
      </div>
    </div>
  );
}

export default page;
