// lib/auth/permissions.ts

export const PERMISSIONS = {
  // Employee
  EMPLOYEE_READ: "EMPLOYEE_READ",
  EMPLOYEE_CREATE: "EMPLOYEE_CREATE",
  EMPLOYEE_UPDATE: "EMPLOYEE_UPDATE",
  EMPLOYEE_DELETE: "EMPLOYEE_DELETE",
  EMPLOYEE_ROLE_MANAGE: "EMPLOYEE_ROLE_MANAGE",

  // Salary / compensation
  SALARY_READ: "SALARY_READ",
  SALARY_UPDATE: "SALARY_UPDATE",

  // Attendance
  ATTENDANCE_READ: "ATTENDANCE_READ",
  ATTENDANCE_UPDATE: "ATTENDANCE_UPDATE",

  // Leads
  LEAD_READ_ASSIGNED: "LEAD_READ_ASSIGNED",
  LEAD_READ_ALL: "LEAD_READ_ALL",
  LEAD_CREATE: "LEAD_CREATE",
  LEAD_UPDATE: "LEAD_UPDATE",
  LEAD_ASSIGN: "LEAD_ASSIGN",

  // Applications
  APPLICATION_READ_ASSIGNED: "APPLICATION_READ_ASSIGNED",
  APPLICATION_READ_ALL: "APPLICATION_READ_ALL",
  APPLICATION_CREATE: "APPLICATION_CREATE",
  APPLICATION_UPDATE: "APPLICATION_UPDATE",

  // Documents
  DOCUMENT_READ: "DOCUMENT_READ",
  DOCUMENT_UPLOAD: "DOCUMENT_UPLOAD",
  DOCUMENT_DELETE: "DOCUMENT_DELETE",

  // Finance
  INVOICE_READ: "INVOICE_READ",
  INVOICE_CREATE: "INVOICE_CREATE",
  INVOICE_UPDATE: "INVOICE_UPDATE",

  PAYMENT_READ: "PAYMENT_READ",
  PAYMENT_CREATE: "PAYMENT_CREATE",

  EXPENSE_READ: "EXPENSE_READ",
  EXPENSE_CREATE: "EXPENSE_CREATE",

  FINANCE_REPORT_READ: "FINANCE_REPORT_READ",

  // Partner / confidential finance
  PARTNER_PROFIT_READ: "PARTNER_PROFIT_READ",

  // Commissions
  COMMISSION_READ: "COMMISSION_READ",
  COMMISSION_UPDATE: "COMMISSION_UPDATE",

  // HR
  HR_READ: "HR_READ",
  HR_CREATE: "HR_CREATE",

  // Credentials
  CREDENTIAL_READ: "CREDENTIAL_READ",
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];