

import { ROLES } from "@/prisma/generated/prisma/client";
import {
  PERMISSIONS,
  type Permission,
} from "./permissions";

export const ROLE_PERMISSIONS: Record<
  ROLES,
  readonly Permission[]
> = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),

  [ROLES.RECEPTION]: [
    PERMISSIONS.LEAD_READ_ASSIGNED,
    PERMISSIONS.EMPLOYEE_READ,
  ],

  [ROLES.TELECALLER]: [
    PERMISSIONS.LEAD_READ_ASSIGNED,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
  ],

  [ROLES.COUNSELOR]: [
    PERMISSIONS.LEAD_READ_ASSIGNED,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.APPLICATION_READ_ASSIGNED,
    PERMISSIONS.APPLICATION_UPDATE,
  ],

  [ROLES.TEACHER]: [
    PERMISSIONS.APPLICATION_READ_ASSIGNED,
    PERMISSIONS.APPLICATION_UPDATE,
  ],

  [ROLES.FILING]: [
    PERMISSIONS.APPLICATION_READ_ASSIGNED,
    PERMISSIONS.APPLICATION_UPDATE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.CREDENTIAL_READ,
  ],

  [ROLES.FINANCE]: [
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_UPDATE,

    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_CREATE,

    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_CREATE,

    PERMISSIONS.FINANCE_REPORT_READ,
    PERMISSIONS.COMMISSION_READ,
  ],

  [ROLES.MARKETING]: [
    PERMISSIONS.LEAD_READ_ALL,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
  ],

  [ROLES.HR]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_ROLE_MANAGE,

    PERMISSIONS.SALARY_READ,
    PERMISSIONS.SALARY_UPDATE,

    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_UPDATE,

    PERMISSIONS.HR_READ,
    PERMISSIONS.HR_CREATE,

    PERMISSIONS.COMMISSION_READ,
  ],
};